[package]

name = "wayland"
version = "0.0.2"
authors = ["Jon Eyolfson <jon@eyl.io>"]
license = "MIT"
repository = "https://github.com/eyolfson/rust-wayland/"
description = """
Simple bindings for Wayland.
"""
